services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: